### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Charliego3** [operatios/lsg#1]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/26761592/100852899-12e17f80-34c2-11eb-8147-f57e6eae2827.png">
<img width="565" alt="image" src="https://user-images.githubusercontent.com/26761592/100852981-30164e00-34c2-11eb-9b7f-b854e5dfa981.png">

can not find these func

I'm using macOS, version: `11.0.1`
go version: `go version go1.15.5 darwin/amd64`

**Comment by operatios** [comment]
Thanks for reporting the issue!
I pushed a new commit that should probably fix it (It builds for darwin/amd64 successfully now, and I also updated the releases with the darwin binary). But, I have no machines to test on, there may still be some bugs I'm unaware of. Please reply if something doesn't work.

**Comment by Charliego3** [comment]
> Thanks for reporting the issue!
> I pushed a new commit that should probably fix it (It builds for darwin/amd64 successfully now, and I also updated the releases with the darwin binary). But, I have no machines to test on, there may still be some bugs I'm unaware of. Please reply if something doesn't work.

Thanks for your reply. Can now run normally.
